@startuml ClassDriverGeneral
skinparam classAttributeIconSize 0

!include ../../ClassGeneral.puml
!include ./ClassDriverRegisterGeneral.puml

class ClassDriverGeneral extends ClassGeneral {
  ' --- Властивості ---
  +timeout: Number - ms період очікування відповіді від приладу
  +regs: Map<String, ClassDriverRegisterGeneral> - список регістрів

  ' --- Конструктор ---
  +ClassDriverGeneral(props: Object) <<constructor>>

  ' --- Методи перевірки ---
  +has(regName: String): boolean - true якщо regName є в regs
  +testRequest(args: {iface, regName, addr}): ClassDriverRegisterGeneral | Error - валідація запитів до getReg/setReg

  ' --- Реєстрація регістрів ---
  +addRegister(props: Object | Array): ClassDriverRegisterGeneral | Array - додає регістр(и) до regs

  ' --- Читання регістра (callback) ---
  +getReg(iface, addr, regName, cb(err, data)): void

  ' --- Читання регістра (Promise) ---
  +getRegPromise(props: {iface, devAddr, regName}): Promise<Array>

  ' --- Запис регістра (callback) ---
  +setReg(iface, addr, regName, value, cb(err, data)): void

  ' --- Запис регістра (Promise) ---
  +setRegPromise(props: {iface, devAddr, regName, value}): Promise<Object>

  ' --- Інформація про регістри ---
  +getRegInfo(regName: String, headers: Array): Object | undefined
  +printRegsDescription(): void - друкує таблицю регістрів у консоль
}

note right of ClassDriverGeneral::getReg
  **iface** - об'єкт з методом send()
  **addr** - адреса приладу (0-254)
  **regName** - id регістру з regs
  **data** = [{regName, value, note, detail:{request, response, afterGet}}]
end note

note right of ClassDriverGeneral::setReg
  **value** - значення для запису
  **data** = {regName, value, note, detail:{duration, request, response, afterSet}}
end note

ClassDriverGeneral o-- "*" ClassDriverRegisterGeneral : regs

@enduml