
@startuml ClassDevManagerRegGeneral_modul

class "ClassDevManagerRegGeneral" {
	---- constructor(props:Object) ----
  
    +**units** ={ ua: ``, en: ``, ru: `` } - одиниці вимірювання 
    + **type** ="text" : {String} - перелік можливих типів регістрів (поки описані в цьому модулі ) 
    + **min** : {Number} - 
    + **max** : {Number} - 
    +**readonly** : {Boolean} - ознака "тільки для читання"
    +**obsolescence** : {Number} - сек, період застарівання даних

	---- this ----
    +**type**
    +**value**
    +**timestamp**
    +**units**
    +**obsolescence**
    +**readonly**
    +**min**
    +**max** 
    +**get/set value()** - зміна значення
    +**isActual()** - повертає true, якщо від часу останньої зміни пройшло менше odsolescense
    +**getAll()** - повертає копію опису регістру 
}

ClassDevManagerRegGeneral <|== ClassGeneral
!include ../../ClassGeneral.puml

@enduml