@startuml ClassStepFlowController
!include ../ClassStep/ClassStepGeneral.puml

class ClassStepFlowController{
    -- /controllers/flowController/ClassStepFlowController.js --
    --

}

ClassStepGeneral <|-- ClassStepFlowController 

@enduml