@startuml ClassTaskGeneral

!include ../regsController/ClassReg_regsList.puml

' -------------  Базовий клас задачі ------------------ 

class ClassTaskGeneral {
	{abstract} getState() : abstaract - має повертати стан задачі 
    {abstract} getStep() : abstaract - має повертати крок для виконання менеджером процессу
    {abstract} getRegForHTML() : abstaract - має повертати опис задачі для редактора програм
    }
ClassReg_regsList <|-- ClassTaskGeneral

@enduml