@startuml ClassTaskGeneral

!include ../regsController/ClassReg_regsList.puml

' -------------  Базовий клас задачі ------------------ 

class ClassTaskGeneral {
	{abstract} getState() : Object 
    {abstract} getStep() : Object
    {abstract} getRegForHTML() : Object

}

ClassReg_regsList <|-- ClassTaskGeneral

@enduml