export default {
  _id: "waiting",
  note: {
    ua: "Очікування",
    en: "Waiting",
    ru: "Ожидание",
  },
  startTime: "",
  type: "",
  duration: "0",
  changed: "2025-10-22T08:52:53.109Z",
  id: "processManager.program::",
  state: "waiting",
  header: {
    ua: "12",
    en: "12",
    ru: "12",
  },
  comment: {
    ua: "Активна програма",
    en: "Active program",
    ru: "Активная программа",
  },
  tasks: [
    {
      id: "description",
      type: "description",
      header: {
        ua: "Загальний опис програми",
        en: "General descriptiom of program",
        ru: "Общее описание программы",
      },
      comment: {
        ua: "some text\n other text\n",
        en: "some text\n other text\n",
        ru: "some text\n other text\n",
      },
      value: "12",
      editable: false,
    },
    {
      _id: "waiting",
      note: {
        ua: "Очікування",
        en: "Waiting",
        ru: "Ожидание",
      },
      startTime: "",
      type: "taskThermal",
      duration: "0",
      changed: "2025-10-22T08:52:53.109Z",
      id: "st_1",
      state: "waiting",
      header: {
        ua: "Термообробка: tT=180; H=90; Y=150",
        en: "Heat treatment: tT=180; H=90; Y=150",
        ru: "Термообработка: tT=180; H=90; Y=150",
      },
      comment: {
        ua: "wT=0; errTmin=-5; errTmax=5; errH=0; regMode=pos; o=-1; ti=0; td=0;",
        en: "wT=0; errTmin=-5; errTmax=5; errH=0; regMode=pos; o=-1; ti=0; td=0;",
        ru: "wT=0; errTmin=-5; errTmax=5; errH=0; regMode=pos; o=-1; ti=0; td=0;",
      },
      tasks: [
        {
          _id: "waiting",
          note: {
            ua: "Очікування",
            en: "Waiting",
            ru: "Ожидание",
          },
          startTime: "",
          type: "heating",
          duration: "0",
          changed: "2025-10-22T08:52:53.109Z",
          id: "heating",
          state: "waiting",
          header: {
            ua: "->180°C",
            en: "->180°C",
            ru: "->180°C",
          },
          comment: {
            ua: "ТРМ251.Нагрівання до 180°C",
            en: "TRM251.Heating to 180°C",
            ru: "ТРМ251.Нагрев до 180°C",
          },
        },
        {
          _id: "waiting",
          note: {
            ua: "Очікування",
            en: "Waiting",
            ru: "Ожидание",
          },
          startTime: "",
          type: "holding",
          duration: "0",
          changed: "2025-10-22T08:52:53.109Z",
          id: "holding",
          state: "waiting",
          header: {
            ua: "= 180°C",
            en: "= 180°C",
            ru: "= 180°C",
          },
          comment: {
            ua: "ТРМ251.Витримка 180°C",
            en: "TRM251.Holding  180°C",
            ru: "ТРМ251.Удержание 180°C",
          },
        },
      ],
    },
    {
      _id: "waiting",
      note: {
        ua: "Очікування",
        en: "Waiting",
        ru: "Ожидание",
      },
      startTime: "",
      type: "taskThermal",
      duration: "0",
      changed: "2025-10-22T08:52:53.109Z",
      id: "st_2",
      state: "waiting",
      header: {
        ua: "Термообробка: tT=300; H=0; Y=30",
        en: "Heat treatment: tT=300; H=0; Y=30",
        ru: "Термообработка: tT=300; H=0; Y=30",
      },
      comment: {
        ua: "wT=0; errTmin=-5; errTmax=5; errH=0; regMode=pos; o=-1; ti=0; td=0;",
        en: "wT=0; errTmin=-5; errTmax=5; errH=0; regMode=pos; o=-1; ti=0; td=0;",
        ru: "wT=0; errTmin=-5; errTmax=5; errH=0; regMode=pos; o=-1; ti=0; td=0;",
      },
      tasks: [
        {
          _id: "waiting",
          note: {
            ua: "Очікування",
            en: "Waiting",
            ru: "Ожидание",
          },
          startTime: "",
          type: "heating",
          duration: "0",
          changed: "2025-10-22T08:52:53.109Z",
          id: "heating",
          state: "waiting",
          header: {
            ua: "->300°C",
            en: "->300°C",
            ru: "->300°C",
          },
          comment: {
            ua: "ТРМ251.Нагрівання до 300°C",
            en: "TRM251.Heating to 300°C",
            ru: "ТРМ251.Нагрев до 300°C",
          },
        },
        {
          _id: "waiting",
          note: {
            ua: "Очікування",
            en: "Waiting",
            ru: "Ожидание",
          },
          startTime: "",
          type: "holding",
          duration: "0",
          changed: "2025-10-22T08:52:53.109Z",
          id: "holding",
          state: "waiting",
          header: {
            ua: "= 300°C",
            en: "= 300°C",
            ru: "= 300°C",
          },
          comment: {
            ua: "ТРМ251.Витримка 300°C",
            en: "TRM251.Holding  300°C",
            ru: "ТРМ251.Удержание 300°C",
          },
        },
      ],
    },
    {
      _id: "waiting",
      note: {
        ua: "Очікування",
        en: "Waiting",
        ru: "Ожидание",
      },
      startTime: "",
      type: "taskThermal",
      duration: "0",
      changed: "2025-10-22T08:52:53.109Z",
      id: "st_3",
      state: "waiting",
      header: {
        ua: "Термообробка: tT=400; H=0; Y=30",
        en: "Heat treatment: tT=400; H=0; Y=30",
        ru: "Термообработка: tT=400; H=0; Y=30",
      },
      comment: {
        ua: "wT=0; errTmin=-5; errTmax=5; errH=0; regMode=pos; o=-1; ti=0; td=0;",
        en: "wT=0; errTmin=-5; errTmax=5; errH=0; regMode=pos; o=-1; ti=0; td=0;",
        ru: "wT=0; errTmin=-5; errTmax=5; errH=0; regMode=pos; o=-1; ti=0; td=0;",
      },
      tasks: [
        {
          _id: "waiting",
          note: {
            ua: "Очікування",
            en: "Waiting",
            ru: "Ожидание",
          },
          startTime: "",
          type: "heating",
          duration: "0",
          changed: "2025-10-22T08:52:53.109Z",
          id: "heating",
          state: "waiting",
          header: {
            ua: "->400°C",
            en: "->400°C",
            ru: "->400°C",
          },
          comment: {
            ua: "ТРМ251.Нагрівання до 400°C",
            en: "TRM251.Heating to 400°C",
            ru: "ТРМ251.Нагрев до 400°C",
          },
        },
        {
          _id: "waiting",
          note: {
            ua: "Очікування",
            en: "Waiting",
            ru: "Ожидание",
          },
          startTime: "",
          type: "holding",
          duration: "0",
          changed: "2025-10-22T08:52:53.109Z",
          id: "holding",
          state: "waiting",
          header: {
            ua: "= 400°C",
            en: "= 400°C",
            ru: "= 400°C",
          },
          comment: {
            ua: "ТРМ251.Витримка 400°C",
            en: "TRM251.Holding  400°C",
            ru: "ТРМ251.Удержание 400°C",
          },
        },
      ],
    },
  ],
  logFileName: "tmp",
};
